site_name: 孤独堡垒
theme:
  name: material
  # custom_dir: overrides
  language: zh
  logo: 'images/logo.jpg'
  favicon: images/logo.jpg
  palette:
      primary: "black"
      accent: "deep orange"
  features:
    - navigation.tabs
plugins:
  - blog


extra:
  social:
    - icon: fontawesome/brands/github
      link: 'https://github.com/smaxad47'